googleAnalyticsID: UA-19387715-3
source: app
destination: public
highlighter: pygments
permalink: /:categories/:title/
paginate: 6
paginate_path: /log/page:num/

kramdown:
  input: GFM
  hard_wrap: false

compress_html:
  clippings: all
  comments: all

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
      description: 'Andrew Wei, codenamed mu, is a software engineer and experience designer.'
  - scope:
      path: 'log'
      type: 'pages'
    values:
      layout: 'log/posts'
      node: log
      return: /log
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'log/post'
      category: log
      node: log
      return: /log
  - scope:
      path: ''
      type: 'drafts'
    values:
      layout: 'log/post'
      category: log
      node: log
      return: /log

exclude:
  - _assets

keep_files:
  - assets
